name: Maven Test

on:
  push:
    branches:
      - 'master'
jobs:
  mvn-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Build with Maven
        shell: bash
        run: |
          mvn test
          
          
